title: Hajar Merbouh
theme: jekllins
author:
  name: Hajar Merbouh
  bio: AI Engineer specializing in ML, NLP, and Knowledge Graphs
  # avatar: /assets/avatar.png  â† optional, can leave this out

social:
  github: https://github.com/hajarmerbouh
  linkedin: https://www.linkedin.com/in/hajarmerbouh/
  email: hajar.merbouh25@gmail.com

